// Code generated by automapper. DO NOT EDIT.

package amgen

import (
	"fmt"

	"github.com/mickamy/automapper/testdata/witherror/converters"
	"github.com/mickamy/automapper/testdata/witherror/model"
	"github.com/mickamy/automapper/testdata/witherror/pb"
)

// FromPbUserPBPtr converts *UserPB to *User.
func FromPbUserPBPtr(src *pb.UserPB) (*model.User, error) {
	if src == nil {
		return nil, nil
	}

	conv0, err := converters.RFC3339ToTime(src.BirthDate)
	if err != nil {
		return nil, fmt.Errorf("BirthDate: %w", err)
	}

	return &model.User{
		ID:        src.Id,
		Name:      src.Name,
		Email:     src.Email,
		BirthDate: conv0,
	}, nil

}

// FromPbUserPB converts UserPB to User.
func FromPbUserPB(src pb.UserPB) (model.User, error) {

	conv0, err := converters.RFC3339ToTime(src.BirthDate)
	if err != nil {
		return model.User{}, fmt.Errorf("BirthDate: %w", err)
	}

	return model.User{
		ID:        src.Id,
		Name:      src.Name,
		Email:     src.Email,
		BirthDate: conv0,
	}, nil

}
