// Code generated by automapper. DO NOT EDIT.

package amgen

import (
	"github.com/mickamy/automapper/testdata/witherror/converters"
	"github.com/mickamy/automapper/testdata/witherror/model"
	"github.com/mickamy/automapper/testdata/witherror/pb"
)

// ToPbUserPBPtr converts *User to *UserPB.
func ToPbUserPBPtr(src *model.User) *pb.UserPB {
	if src == nil {
		return nil
	}

	return &pb.UserPB{
		Id:        src.ID,
		Name:      src.Name,
		Email:     src.Email,
		BirthDate: converters.TimeToRFC3339(src.BirthDate),
	}

}

// ToPbUserPB converts User to UserPB.
func ToPbUserPB(src model.User) pb.UserPB {

	return pb.UserPB{
		Id:        src.ID,
		Name:      src.Name,
		Email:     src.Email,
		BirthDate: converters.TimeToRFC3339(src.BirthDate),
	}

}
