// Code generated by automapper. DO NOT EDIT.

package amgen

import (
	"github.com/mickamy/automapper/testdata/advanced/converters"
	"github.com/mickamy/automapper/testdata/advanced/model"
	"github.com/mickamy/automapper/testdata/advanced/pb"
)

// FromPbOrderPBPtr converts *OrderPB to *Order.
func FromPbOrderPBPtr(src *pb.OrderPB) *model.Order {
	if src == nil {
		return nil
	}

	return &model.Order{
		ID:          src.OrderId,
		ProductName: src.ProductName,
		Quantity:    src.Quantity,
		CreatedAt:   converters.UnixToTime(src.CreatedAt),
		Status:      converters.Int32ToStatus(src.Status),
		Items: func() []model.OrderItem {
			if src.Items == nil {
				return nil
			}
			result := make([]model.OrderItem, len(src.Items))
			for i, v := range src.Items {
				result[i] = FromPbOrderItemPB(*v)
			}
			return result
		}(),
	}

}

// FromPbOrderPB converts OrderPB to Order.
func FromPbOrderPB(src pb.OrderPB) model.Order {

	return model.Order{
		ID:          src.OrderId,
		ProductName: src.ProductName,
		Quantity:    src.Quantity,
		CreatedAt:   converters.UnixToTime(src.CreatedAt),
		Status:      converters.Int32ToStatus(src.Status),
		Items: func() []model.OrderItem {
			if src.Items == nil {
				return nil
			}
			result := make([]model.OrderItem, len(src.Items))
			for i, v := range src.Items {
				result[i] = FromPbOrderItemPB(*v)
			}
			return result
		}(),
	}

}

// FromPbOrderItemPBPtr converts *OrderItemPB to *OrderItem.
func FromPbOrderItemPBPtr(src *pb.OrderItemPB) *model.OrderItem {
	if src == nil {
		return nil
	}

	return &model.OrderItem{
		SKU:      src.Sku,
		Name:     src.Name,
		Quantity: src.Quantity,
		Price:    src.Price,
	}

}

// FromPbOrderItemPB converts OrderItemPB to OrderItem.
func FromPbOrderItemPB(src pb.OrderItemPB) model.OrderItem {

	return model.OrderItem{
		SKU:      src.Sku,
		Name:     src.Name,
		Quantity: src.Quantity,
		Price:    src.Price,
	}

}
