// Code generated by automapper. DO NOT EDIT.

package amgen

import (
	"github.com/mickamy/automapper/testdata/advanced/converters"
	"github.com/mickamy/automapper/testdata/advanced/model"
	"github.com/mickamy/automapper/testdata/advanced/pb"
)

// ToPbOrderPBPtr converts *Order to *OrderPB.
func ToPbOrderPBPtr(src *model.Order) *pb.OrderPB {
	if src == nil {
		return nil
	}

	return &pb.OrderPB{
		OrderId:     src.ID,
		ProductName: src.ProductName,
		Quantity:    src.Quantity,
		CreatedAt:   converters.TimeToUnix(src.CreatedAt),
		Status:      converters.StatusToInt32(src.Status),
		Items: func() []*pb.OrderItemPB {
			if src.Items == nil {
				return nil
			}
			result := make([]*pb.OrderItemPB, len(src.Items))
			for i, v := range src.Items {
				result[i] = ToPbOrderItemPBPtr(&v)
			}
			return result
		}(),
	}

}

// ToPbOrderPB converts Order to OrderPB.
func ToPbOrderPB(src model.Order) pb.OrderPB {

	return pb.OrderPB{
		OrderId:     src.ID,
		ProductName: src.ProductName,
		Quantity:    src.Quantity,
		CreatedAt:   converters.TimeToUnix(src.CreatedAt),
		Status:      converters.StatusToInt32(src.Status),
		Items: func() []*pb.OrderItemPB {
			if src.Items == nil {
				return nil
			}
			result := make([]*pb.OrderItemPB, len(src.Items))
			for i, v := range src.Items {
				result[i] = ToPbOrderItemPBPtr(&v)
			}
			return result
		}(),
	}

}

// ToPbOrderItemPBPtr converts *OrderItem to *OrderItemPB.
func ToPbOrderItemPBPtr(src *model.OrderItem) *pb.OrderItemPB {
	if src == nil {
		return nil
	}

	return &pb.OrderItemPB{
		Sku:      src.SKU,
		Name:     src.Name,
		Quantity: src.Quantity,
		Price:    src.Price,
	}

}

// ToPbOrderItemPB converts OrderItem to OrderItemPB.
func ToPbOrderItemPB(src model.OrderItem) pb.OrderItemPB {

	return pb.OrderItemPB{
		Sku:      src.SKU,
		Name:     src.Name,
		Quantity: src.Quantity,
		Price:    src.Price,
	}

}
