// Code generated by automapper. DO NOT EDIT.

package amgen

import (
	"github.com/mickamy/automapper/testdata/advanced/converters"
	"github.com/mickamy/automapper/testdata/advanced/model"
	"github.com/mickamy/automapper/testdata/advanced/pb"
)

// ToPbProductPBPtr converts *Product to *ProductPB.
func ToPbProductPBPtr(src *model.Product) *pb.ProductPB {
	if src == nil {
		return nil
	}

	return &pb.ProductPB{
		Id:    src.ID,
		Name:  src.Name,
		Price: converters.PriceStringToCents(src.Price),
	}

}

// ToPbProductPB converts Product to ProductPB.
func ToPbProductPB(src model.Product) pb.ProductPB {

	return pb.ProductPB{
		Id:    src.ID,
		Name:  src.Name,
		Price: converters.PriceStringToCents(src.Price),
	}

}
