package generator

import "text/template"

// Templates for code generation.
var templates = template.Must(template.New("").Funcs(funcMap).Parse(`
{{define "file"}}
// Code generated by automapper. DO NOT EDIT.

package {{.PackageName}}

{{if .Imports}}
import (
{{range .Imports}}	"{{.}}"
{{end}})
{{end}}

{{range .Functions}}
{{template "function" .}}
{{end}}
{{end}}

{{define "function"}}
{{if .IsPointer}}
// {{.Name}} converts *{{.SourceType}} to {{if .ReturnsPointer}}*{{end}}{{.TargetType}}.
func {{.Name}}(src *{{.SourceQualified}}) {{if .HasError}}({{end}}{{if .ReturnsPointer}}*{{end}}{{.TargetQualified}}{{if .HasError}}, error){{end}} {
	if src == nil {
		return {{if .HasError}}nil, nil{{else}}nil{{end}}
	}
{{if .HasError}}{{template "body_with_error" .}}{{else}}{{template "body_no_error" .}}{{end}}
}
{{else}}
// {{.Name}} converts {{.SourceType}} to {{.TargetType}}.
func {{.Name}}(src {{.SourceQualified}}) {{if .HasError}}({{end}}{{.TargetQualified}}{{if .HasError}}, error){{end}} {
{{if .HasError}}{{template "body_with_error" .}}{{else}}{{template "body_no_error" .}}{{end}}
}
{{end}}
{{end}}

{{define "body_no_error"}}
	return {{if .ReturnsPointer}}&{{end}}{{.TargetQualified}}{
{{range .Fields}}{{template "field_assignment" .}}
{{end}}	}
{{end}}

{{define "body_with_error"}}
{{range .Fields}}{{if .HasError}}{{template "error_field_prep" .}}
{{end}}{{end}}
	return {{if .ReturnsPointer}}&{{end}}{{.TargetQualified}}{
{{range .Fields}}{{template "field_assignment_with_var" .}}
{{end}}	}, nil
{{end}}

{{define "field_assignment"}}
{{- if eq .Kind "direct" -}}
		{{.TargetField}}: src.{{.SourceField}},
{{- else if eq .Kind "converter" -}}
		{{.TargetField}}: {{.ConverterCall}}(src.{{.SourceField}}),
{{- else if eq .Kind "nested" -}}
		{{.TargetField}}: {{.NestedCall}},
{{- else if eq .Kind "slice" -}}
		{{.TargetField}}: {{.SliceCall}},
{{- end -}}
{{end}}

{{define "field_assignment_with_var"}}
{{- if .HasError -}}
		{{.TargetField}}: {{.VarName}},
{{- else if eq .Kind "direct" -}}
		{{.TargetField}}: src.{{.SourceField}},
{{- else if eq .Kind "converter" -}}
		{{.TargetField}}: {{.ConverterCall}}(src.{{.SourceField}}),
{{- else if eq .Kind "nested" -}}
		{{.TargetField}}: {{.NestedCall}},
{{- else if eq .Kind "slice" -}}
		{{.TargetField}}: {{.SliceCall}},
{{- end -}}
{{end}}

{{define "error_field_prep"}}
	{{.VarName}}, err := {{.ConverterCall}}(src.{{.SourceField}})
	if err != nil {
		return {{.NilOrZero}}, fmt.Errorf("{{.TargetField}}: %w", err)
	}
{{end}}
`))

var funcMap = template.FuncMap{
	"lower": func(s string) string {
		if len(s) == 0 {
			return s
		}

		return string(s[0]|32) + s[1:]
	},
}
