// Code generated by automapper. DO NOT EDIT.

package amgen

import (
	"github.com/mickamy/automapper/testdata/simple/model"
	"github.com/mickamy/automapper/testdata/simple/pb"
)

// ToPbUserPBPtr converts *User to *UserPB.
func ToPbUserPBPtr(src *model.User) *pb.UserPB {
	if src == nil {
		return nil
	}

	return &pb.UserPB{
		Id:      src.ID,
		Name:    src.Name,
		Email:   src.Email,
		Active:  src.Active,
		Tags:    src.Tags,
		Address: ToPbAddressPBPtr(src.Address),
	}

}

// ToPbUserPB converts User to UserPB.
func ToPbUserPB(src model.User) pb.UserPB {

	return pb.UserPB{
		Id:      src.ID,
		Name:    src.Name,
		Email:   src.Email,
		Active:  src.Active,
		Tags:    src.Tags,
		Address: ToPbAddressPBPtr(src.Address),
	}

}

// ToPbAddressPBPtr converts *Address to *AddressPB.
func ToPbAddressPBPtr(src *model.Address) *pb.AddressPB {
	if src == nil {
		return nil
	}

	return &pb.AddressPB{
		Street:  src.Street,
		City:    src.City,
		Country: src.Country,
	}

}

// ToPbAddressPB converts Address to AddressPB.
func ToPbAddressPB(src model.Address) pb.AddressPB {

	return pb.AddressPB{
		Street:  src.Street,
		City:    src.City,
		Country: src.Country,
	}

}
