// Code generated by automapper. DO NOT EDIT.

package amgen

import (
	"github.com/mickamy/automapper/testdata/simple/model"
	"github.com/mickamy/automapper/testdata/simple/pb"
)

// FromPbUserPBPtr converts *UserPB to *User.
func FromPbUserPBPtr(src *pb.UserPB) *model.User {
	if src == nil {
		return nil
	}

	return &model.User{
		ID:      src.Id,
		Name:    src.Name,
		Email:   src.Email,
		Active:  src.Active,
		Tags:    src.Tags,
		Address: FromPbAddressPBPtr(src.Address),
	}

}

// FromPbUserPB converts UserPB to User.
func FromPbUserPB(src pb.UserPB) model.User {

	return model.User{
		ID:      src.Id,
		Name:    src.Name,
		Email:   src.Email,
		Active:  src.Active,
		Tags:    src.Tags,
		Address: FromPbAddressPBPtr(src.Address),
	}

}

// FromPbAddressPBPtr converts *AddressPB to *Address.
func FromPbAddressPBPtr(src *pb.AddressPB) *model.Address {
	if src == nil {
		return nil
	}

	return &model.Address{
		Street:  src.Street,
		City:    src.City,
		Country: src.Country,
	}

}

// FromPbAddressPB converts AddressPB to Address.
func FromPbAddressPB(src pb.AddressPB) model.Address {

	return model.Address{
		Street:  src.Street,
		City:    src.City,
		Country: src.Country,
	}

}
